### ISSUE TITLE
Settings Not Updating 

### ISSUE THREAD

**Issue by Z3r0CooLE** [YariKartoshe4ka/sublime-svg-viewer#4]
I have installed inkscape-cli and inkscape is in my path, I can use it in terminal and SVG Preview works, but I wanted to give this a try. When I run View SVG an alert pops with the error: "None" converter not supported. Please choose converter only from suggested list!
I have saved the config with force_offline_mode=true and "engine": "inkscape" under offline.
Inkscape is also listed in my providers.

**Comment by Z3r0CooLE** [comment]
Manually removing the package and re-installing with package control seems to have resolved the issue, but I also don't know why the first installation had a buggy result.

**Comment by YariKartoshe4ka** [comment]
I'm not sure if this is a bug. Rather, it's a matter of incorrect configuration. Such an error could only occur if you redefined the offline section and forgot to specify the converter (although you seem to have specified it?):

<table>
<tr>
    <th>Stock config</th>
    <th>User config</th>
</tr>
<tr>
<td>

```js
{
    ...

    // Offline mode settings of converter
    "offline": {
        // Convert engine, can be one from `converters.json`
        "engine": "inkscape",
    }
}
```

</td>
<td>

```js
{
    "force_offline_mode": true,
    "offline": {},
    "engine": "inkscape"
}

```

</td>
</tr>
</table>

However, I recommend changing the converter through a special command **"SVG Viewer: Change Offline/Online Converter"**
